server {
    server_name promo.vera-eterna.ru;

    root "/home/direkt_analitika_v3_admin/Вера Этериа/promo.vera-eterna.ru";
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ^~ /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location ~ /\. {
        deny all;
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/promo.vera-eterna.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/promo.vera-eterna.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = promo.vera-eterna.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name promo.vera-eterna.ru;
    return 404; # managed by Certbot


}