server {
    listen 80;
    listen [::]:80;
    server_name promo.vera-eterna.ru;

    root "/home/direkt_analitika_v3_admin/Вера Этериа/promo.vera-eterna.ru";
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ^~ /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location ~ /\. {
        deny all;
    }
}
